---
title: "ARosado Physiology Lab 1 - Ion Channel"
author: "Avery Rosado"
date: "1/18/2021"
output: 
    html_document:
      theme: cosmo
      toc: yes
---

# Part II: Probability and Stochastic Behavior
```{R}
# Coin Toss
flip <- 10
outcomes <- rep(0,flip)
for(i in 1:flip){
  x <-runif(1)
  if(x<0.5){
    outcomes[i] <- 0 # heads
  }
  else{
    outcomes[i] <- 1 # tails
  }
}
print(paste("There are", sum(outcomes), "heads and", (10-sum(outcomes)),"tails."))
mean <- mean(outcomes)
print(paste("Mean flip result given 10 flips:",mean))
```
## 4. What is the size of the flip result array?
### 1x10

## 5. Record the average value of the flip result given 10 flips of the coin (enter as a comment). Is it 0.5? 
### Run 1: 0.6; Run 2: 0.4; Run 3: 0.5. Therefore, the average value up the flip result given 10 flips is 0.5 (see also code above). 

### *Plot the results of flip result (0's or 1's) verses the number of flips.* 
```{R}
cl=rainbow(2)
# Coin Toss
flip <- 10
flips <- seq(1,10,1)
outcomes <- rep(0,flip)
for(i in 1:flip){
  x <-runif(1)
  if(x<0.5){
    outcomes[i] <- 0 # heads
  }
  else{
    outcomes[i] <- 1 # tails
  }
}
mean <- mean(outcomes)
# print(paste("There are", sum(outcomes), "heads and", (10-sum(outcomes)),"tails."))
# print(paste("Mean flip result given 10 flips:",mean(outcomes)))
plot(flips,outcomes,xlab="No. Flips",ylab="Flip Results",type="o",xlim=c(0,10),ylim=c(0,1),col=cl[1])
abline(mean,0, col=cl[2])
legend("bottomleft", bty="n", legend=c("Outcomes","Mean Outcome"), inset=0.0, fill=cl[1:2],cex=0.8)





```

## 6. Comment on the findings of the graph. If you re-reun the code 3 times, does the profile of the graph change? Comment on the changes.
### The graph mirrors the stochastic behavior of ion channels; it repeatedly "oscillates" between outcomes of 1.0 and 0.0, apparently randomly, from toss to toss. As the code is the code is run repeatedly, This random behavior is repeatedly observed. The mean rises and falls, almost always on R: [0.2,0.8]. Though the number of flips is low, even the mean in this scenario does not rise and fall to the utmost extremes of the graph. 

## 7. Write a sentence explaining why larger number of flips gives a mean closer to 0.5.
### As the number of flips increases, the 0.5 probability of landing on either face of the coin is more likely to be attained as frequency of both outcomes rises. Eventually, given infinite trials, the calculated probability will repeatedly be achieved. 