---
title: "ARosado_Lab5_Fri"
author: "Avery Rosado"
date: "10/30/2020"
output:
  word_document:
    toc: yes
  pdf_document:
    toc: yes
  html_document:
    theme: cosmo
    toc: yes
---

# PART I: Introduction
```{R parameter reference}
gamma<-1  #time^-1
betaX<-4  #concentration/time
betaY<-1  #concentration/time
alphaX<-5  #time^-1
alphaY<-0.3  #time^-1
K<-0.5  #concentration (a.u)
L<-0.3  #concentration (a.u)
m<-4
n<-3
ComS_int<-1  #concentration (a.u)
ComK_int<-1  #concentration (a.u)
```

```{R #1: Concentration vs. Time}
cl=rainbow(2)
gamma<-1  #time^-1
betaX<-4  #concentration/time
betaY<-1  #concentration/time
alphaX<-5  #time^-1
alphaY<-0.3  #time^-1
K<-0.5  #concentration (a.u)
L<-0.3  #concentration (a.u)
m<-4
n<-3
ComS_int<-1  #concentration (a.u)
ComK_int<-1  #concentration (a.u)

p<-c(gamma=gamma,betaX=betaX,betaY=betaY,alphaX=alphaX,alphaY=alphaY,K=K,L=L,m=m,n=n)  #parameters
y0<-c(ComK=ComK_int,ComS=ComS_int)  #initial conditions
times<-seq(0,100,0.001)  #time array

library(deSolve)  #ode solver
func<-function(t,y,p){
  ComK<-y[1]
  ComS<-y[2]
  with(as.list(p),{
    dComK<-gamma*ComS+betaX*(ComK^n/((ComK^n)+(K^n)))-alphaX*ComK
    dComS<-betaY*(L^m/((ComK^m)+(L^m)))-alphaY*ComS
    return(list(c(dComK,dComS)))
  })
}
out<-ode(y=y0,times,func,p)  #call ODE solver
plot(out[,1],out[,2],type="l",xlab="Time",ylab="Concentration (a.u)", main="ComK,ComS Concentrations over Time", col=cl[1])  
lines(out[,1],out[,3],col=cl[2])
legend("topright", legend=c("[ComK]","[ComS]"), fill =cl[1:2])

```
```{R #2: Trajectory in the phase plane}
gamma<-1  #time^-1
betaX<-4  #concentration/time
betaY<-1  #concentration/time
alphaX<-5  #time^-1
alphaY<-0.3  #time^-1
K<-0.5  #conenctration (a.u)
L<-0.3  #conenctration (a.u)
m<-4
n<-3
ComS_int<-1  #concentration (a.u)
ComK_int<-1  #concentration (a.u)

p<-c(gamma=gamma,betaX=betaX,betaY=betaY,alphaX=alphaX,alphaY=alphaY,K=K,L=L,m=m,n=n)  #parameters
y0<-c(ComK=ComK_int,ComS=ComS_int)  #initial conditions
times<-seq(0,100,0.001)  #time array

library(deSolve)  #ode solver
func<-function(t,y,p){
  ComK<-y[1]
  ComS<-y[2]
  with(as.list(p),{
    dComK<-gamma*ComS+betaX*(ComK^n/((ComK^n)+(K^n)))-alphaX*ComK
    dComS<-betaY*(L^m/((ComK^m)+(L^m)))-alphaY*ComS
    return(list(c(dComK,dComS)))
  })
}
out<-ode(y=y0,times,func,p)  #call ODE solver
plot(out[,2],out[,3],type="l",xlab="[ComS]",ylab="[ComK]", main="ComK,ComS Concentration Trajectory", col="purple")

```

#3: Comment
Graph I shows oscillations in the concentrations of ComK and ComS over a time interval. There appears to be some lag in oscillations of ComK compared with the oscillations of ComS;  ComS reaches the minumum point of any given oscillation, and ComK only reaches this minimum trajectory shortly thereafter. This 'lag' corresponds with a horizontal shift in ComK oscillations that seems to be caused by initially low rate of decrease in [ComK]. ComK decrease steepens at roughly time=5. This pattern of rate of decrease of ComK steepening persists over the time course. This is not the case for ComS, which exhibits unifrom oscillations. The range over which ComK oscillates is shifted vertically downward compared with ComS. Amplitudes for each component's oscillations appear to be roughly equivalent, at ~0.6, and frequency also appears to be roughly equivalent. 

In the phase plane, a line emerges from the rounded trajectory and stops at the point (1,1). From here, there is a drop-off in both components' concentrations that reaches a minimum at roughly (0.55,0.4). After this point, [ComS] continues to decrease while [ComK] begins toincrease. At roughly (0.2,0.8), both components begin increasing together before [ComK] begins to decrease once again after surpassing concentration=1.1. Finally, both ComK and ComS begin are returned to their original state at roughly (0.8,0.8) and the circle is looped. There is a great deal of interplay between ComK and ComS, marked by various thresholds in each component's respective concentrations that results an apparent cycle, with a graph that very roughly corresponds to the result of graphing cos(theta) vs cos(theta).

```{R #4: Nullclines}
cl<-rainbow(2)
gamma<-1  #time^-1
betaX<-4  #concentration/time
betaY<-1  #concentration/time
alphaX<-5  #time^-1
alphaY<-0.3  #time^-1
K<-0.5  #concentration (a.u)
L<-0.3  #concentration (a.u)
m<-4
n<-3
ComS_int<-1  #concentration (a.u)
ComK_int<-1  #concentration (a.u)
times<-seq(0,100,0.001)  #time array

X_Null<-seq(0,2,0.01)  #values of ComK (X) 
ComK_Null<-((alphaX/gamma)*X_Null)-(betaX/gamma)*((X_Null^n)/((X_Null^n)+(K^n)))
ComS_Null<-(betaY/alphaY)*((L^m)/((L^m)+(X_Null^m)))

plot(X_Null,ComK_Null,type="l",xlab="[ComS]",ylab="[ComK]",main="[ComS] vs. [ComK] (Nullclines in the phase plane)",col=cl[1],xlim=c(0,1),ylim=c(0,2))
lines(X_Null,ComS_Null,col=cl[2])
legend("topright", inset=0.05, legend=c("[ComS]","[ComK]"), fill =cl[1:2])

```

```{R #5: Nullclines + Trajectory Visual}
cl<-rainbow(2)
gamma<-1  #time^-1
betaX<-4  #concentration/time
betaY<-1  #concentration/time
alphaX<-5  #time^-1
alphaY<-0.3  #time^-1
K<-0.5  #concentration (a.u)
L<-0.3  #concentration (a.u)
m<-4
n<-3
ComS_int<-1  #concentration (a.u)
ComK_int<-1  #concentration (a.u)
times<-seq(0,100,0.001)  #time array

X_Null<-seq(0,4,0.001)  #values of ComK (X) 
ComK_Null<-((alphaX/gamma)*X_Null)-(betaX/gamma)*((X_Null^n)/((X_Null^n)+(K^n)))
ComS_Null<-(betaY/alphaY)*((L^m)/((L^m)+(X_Null^m)))

p<-c(gamma=gamma,betaX=betaX,betaY=betaY,alphaX=alphaX,alphaY=alphaY,K=K,L=L,m=m,n=n)  #parameters
y0<-c(ComK=ComK_int,ComS=ComS_int)  #initial conditions
times<-seq(0,100,0.001)  #time array

library(deSolve)  #ode solver
func<-function(t,y,p){
  ComK<-y[1]
  ComS<-y[2]
  with(as.list(p),{
    dComK<-gamma*ComS+betaX*(ComK^n/((ComK^n)+(K^n)))-alphaX*ComK
    dComS<-betaY*(L^m/((ComK^m)+(L^m)))-alphaY*ComS
    return(list(c(dComK,dComS)))
  })
}
out<-ode(y=y0,times,func,p)  #call ODE solver

plot(X_Null,ComK_Null,type="l",xlab="[ComS]",ylab="[ComK]",main="[ComS] vs. [ComK] (Nullclines in the phase plane)",col=cl[1],xlim=c(0,1),ylim=c(0,2))
lines(X_Null,ComS_Null,col=cl[2])
lines(out[,2],out[,3],col="purple")


legend("topright", inset = 0.00, legend=c("[ComS]","[ComK]","Concentration Trajectory"), fill=c(cl[1],cl[2],"purple"))
```
#6
The nullclines cross at roughly (0.45,0.6). This fixed point represents the point at which dComK/dt and dComS/dt are both equal to 0 and the system achieves steady state; system dynamics show no change. 
```{R #6}
#Plot the trajectory of 3 more initial conditions for ComK and ComS on the same phase plane graph
cl<-rainbow(5)
gamma<-1  #time^-1
betaX<-4  #concentration/time
betaY<-1  #concentration/time
alphaX<-5  #time^-1
alphaY<-0.3  #time^-1
K<-0.5  #concentration (a.u)
L<-0.3  #concentration (a.u)
m<-4
n<-3
times<-seq(0,100,0.001)  #time array

#Initial Condition 1: ComK=0.7 ; ComS=1
X_Null<-seq(0,4,0.001)  #values of ComK (X) 
ComK_Null<-((alphaX/gamma)*X_Null)-(betaX/gamma)*((X_Null^n)/((X_Null^n)+(K^n)))
ComS_Null<-(betaY/alphaY)*((L^m)/((L^m)+(X_Null^m)))
ComS_int1<-1  #concentration (a.u)
ComK_int1<-.7  #concentration (a.u)
p<-c(gamma=gamma,betaX=betaX,betaY=betaY,alphaX=alphaX,alphaY=alphaY,K=K,L=L,m=m,n=n)  #parameters
y01<-c(ComK=ComK_int1,ComS=ComS_int1)  #initial conditions
times<-seq(0,100,0.001)  #time array

library(deSolve)  #ode solver
func<-function(t,y,p){
  ComK<-y[1]
  ComS<-y[2]
  with(as.list(p),{
    dComK<-gamma*ComS+betaX*(ComK^n/((ComK^n)+(K^n)))-alphaX*ComK
    dComS<-betaY*(L^m/((ComK^m)+(L^m)))-alphaY*ComS
    return(list(c(dComK,dComS)))
  })
}
out1<-ode(y=y01,times,func,p)  #call ODE solver


#Initial Condition 2: ComK=1 ; ComS=.7
X_Null<-seq(0,4,0.001)  #values of ComK (X) 
ComK_Null<-((alphaX/gamma)*X_Null)-(betaX/gamma)*((X_Null^n)/((X_Null^n)+(K^n)))
ComS_Null<-(betaY/alphaY)*((L^m)/((L^m)+(X_Null^m)))

p<-c(gamma=gamma,betaX=betaX,betaY=betaY,alphaX=alphaX,alphaY=alphaY,K=K,L=L,m=m,n=n)  #parameters
ComS_int2<-.7  #concentration (a.u)
ComK_int2<-1  #concentration (a.u)
y02<-c(ComK=ComK_int2,ComS=ComS_int2)  #initial conditions
times<-seq(0,100,0.001)  #time array

func<-function(t,y,p){
  ComK<-y[1]
  ComS<-y[2]
  with(as.list(p),{
    dComK<-gamma*ComS+betaX*(ComK^n/((ComK^n)+(K^n)))-alphaX*ComK
    dComS<-betaY*(L^m/((ComK^m)+(L^m)))-alphaY*ComS
    return(list(c(dComK,dComS)))
  })
}
out2<-ode(y=y02,times,func,p)  #call ODE solver


#Initial Condition 3: ComK=.7 ; ComS=.7
X_Null<-seq(0,4,0.001)  #values of ComK (X) 
ComK_Null<-((alphaX/gamma)*X_Null)-(betaX/gamma)*((X_Null^n)/((X_Null^n)+(K^n)))
ComS_Null<-(betaY/alphaY)*((L^m)/((L^m)+(X_Null^m)))

p<-c(gamma=gamma,betaX=betaX,betaY=betaY,alphaX=alphaX,alphaY=alphaY,K=K,L=L,m=m,n=n)  #parameters
ComS_int3<-.7  #concentration (a.u)
ComK_int3<-.7  #concentration (a.u)
y03<-c(ComK=ComK_int3,ComS=ComS_int3)  #initial conditions
times<-seq(0,100,0.001)  #time array

func<-function(t,y,p){
  ComK<-y[1]
  ComS<-y[2]
  with(as.list(p),{
    dComK<-gamma*ComS+betaX*(ComK^n/((ComK^n)+(K^n)))-alphaX*ComK
    dComS<-betaY*(L^m/((ComK^m)+(L^m)))-alphaY*ComS
    return(list(c(dComK,dComS)))
  })
}
out3<-ode(y=y03,times,func,p)  #call ODE solver

plot(X_Null,ComK_Null,type="l",xlab="[ComS]",ylab="[ComK]",main="[ComS] vs. [ComK] (Nullclines in the phase plane)",col=cl[1],xlim=c(0,1),ylim=c(0,2))
lines(X_Null,ComS_Null,col=cl[2])
lines(out1[,2],out1[,3],col=cl[3])
lines(out2[,2],out2[,3],col=cl[4])
lines(out3[,2],out3[,3],col=cl[5])
legend("topright", inset = 0.00, legend=c("[ComS]","[ComK]","Trajectory1","Trajectory 2", "Trajectory 3"), fill=c(cl[1],cl[2],cl[3],cl[4],cl[5]))


```
#6 (cont'd)
Though the main cyclical area of the trajectory is preserved when initial concentrations are changed, the starting points differ=; even as the system moves from the starting point into the cycle, the relationship between concentrations noted above can be observed. For example, in Trajectory 3, the line extending from the starting point is roughly adjacent to that of the main cycle. The fixed point observed at the intersection of the nullcines for [ComS] and [ComK] are stable (all eigenvalues have negative real parts). After deviation from this equilibrium point there will be a return to equilibrium. 

# PART III: Monostability: low levels of ComK - *Vegetative State*
```{R #7,8: Prevent oscillations (tuning parameters)}
cl=rainbow(2)
#gamma<-1  #time^-1
#betaX<-3.5  #concentration/time; DECREASE
#betaY<-2.5  #concentration/time; INCREASE
#alphaX<-5  #time^-1
#alphaY<-0.2  #time^-1; DECREASE
#K<-0.5  #conenctration (a.u)
#L<-0.3  #conenctration (a.u)
#m<-4
#n<-4.1

gamma<-1  #time^-1
betaX<-4  #concentration/time
betaY<-1  #concentration/time
alphaX<-5  #time^-1
alphaY<-1.5  #time^-1
K<-0.5  #conenctration (a.u)
L<-0.3  #conenctration (a.u)
m<-4
n<-4.1
ComS_int<-1  #concentration (a.u)
ComK_int<-1  #concentration (a.u)
times<-seq(0,100,0.001)  #time array
ComS_int<-1  #concentration (a.u)
ComK_int<-1  #concentration (a.u)

p<-c(gamma=gamma,betaX=betaX,betaY=betaY,alphaX=alphaX,alphaY=alphaY,K=K,L=L,m=m,n=n)  #parameters
y0<-c(ComK=ComK_int,ComS=ComS_int)  #initial conditions
times<-seq(0,100,0.001)  #time array

library(deSolve)  #ode solver
func<-function(t,y,p){
  ComK<-y[1]
  ComS<-y[2]
  with(as.list(p),{
    dComK<-gamma*ComS+betaX*(ComK^n/((ComK^n)+(K^n)))-alphaX*ComK
    dComS<-betaY*(L^m/((ComK^m)+(L^m)))-alphaY*ComS
    return(list(c(dComK,dComS)))
  })
}
out<-ode(y=y0,times,func,p)  #call ODE solver
plot(out[,1],out[,2],type="l",xlab="Time",ylab="Concentration (a.u)", main="ComK,ComS Concentrations over Time", col=cl[1],ylim=c(0,1.1))  
lines(out[,1],out[,3],col=cl[2])
legend("topright", legend=c("[ComK]","[ComS]"), fill =cl[1:2])
```
#7 (cont'd)
Monostability was arrived at after significantly icnrease alphaY. 

#8 (cont'd)
Both concentrations drop off in an identical manner to their original oscillations ([ComS] exhibits a slightly steepened decrease in concentration compared with ComS). By time=210, each line has reached the steady state, where it remains for the remainder of the time interval. There is some semblance of oscillation between time=0 and time=5 prior to steady state. For the altered parameters listed above, the two steady states exist at [ComK]=~.15 a.u and [ComS]=~0.61 When both compounds are at these concentrations, the system exhibits no oscillation, and there is no fluctuation in concentration; dComK/dt and dComS/dt are equal to 0 for an extended period of time. 

(It can be noted that, as show in the comments above, monostability can also be achieved by decreasing AlphaY and BetaX, and increasing BetaY)

```{R #9: Nullclines, lowered alphaY}
cl<-rainbow(2)
#gamma<-1  #time^-1
#betaX<-3.5  #concentration/time
#betaY<-2.5  #concentration/time
#alphaX<-5  #time^-1
#alphaY<-0.2  #time^-1
#K<-0.5  #conenctration (a.u)
#L<-0.3  #conenctration (a.u)
#m<-4
#n<-4.1
#ComS_int<-1  #concentration (a.u)
#ComK_int<-1  #concentration (a.u)
#times<-seq(0,100,0.001)  #time array

gamma<-1  #time^-1
betaX<-4  #concentration/time
betaY<-1  #concentration/time
alphaX<-5  #time^-1
alphaY<-1.5  #time^-1
K<-0.5  #conenctration (a.u)
L<-0.3  #conenctration (a.u)
m<-4
n<-4.1
ComS_int<-1  #concentration (a.u)
ComK_int<-1  #concentration (a.u)
times<-seq(0,100,0.001)  #time array

X_Null<-seq(0,2,0.01)  #values of ComK (X) 
ComK_Null<-((alphaX/gamma)*X_Null)-(betaX/gamma)*((X_Null^n)/((X_Null^n)+(K^n)))
ComS_Null<-(betaY/alphaY)*((L^m)/((L^m)+(X_Null^m)))

plot(X_Null,ComK_Null,type="l",xlab="[ComS]",ylab="[ComK]",main="[ComS] vs. [ComK] (Nullclines in the phase plane)",col=cl[1],xlim=c(0,1),ylim=c(0,2))
lines(X_Null,ComS_Null,col=cl[2])
legend("topright", legend=c("[ComS]","[ComK]"), fill =cl[1:2])

```
#9 (cont'd)
The fixed point exists at roughly (0.1,0.6). At these concentrations steady state is achieved, thus there are no fluctuations in the system output. The fixed point exists at [ComK]=~.15 a.u and [ComS]=~0.61

```{R #10 }
#Plot the trajectory of 3 more initial conditions for ComK and ComS on the same phase plane graph
cl<-rainbow(5)
#gamma<-1  #time^-1
#betaX<-3.5  #concentration/time
#betaY<-2.5  #concentration/time
#alphaX<-5  #time^-1
#alphaY<-0.2  #time^-1
#K<-0.5  #conenctration (a.u)
#L<-0.3  #conenctration (a.u)
#m<-4
#n<-4.1
#ComS_int<-1  #concentration (a.u)
#ComK_int<-1  #concentration (a.u)
#times<-seq(0,100,0.001)  #time array

gamma<-1  #time^-1
betaX<-4  #concentration/time
betaY<-1  #concentration/time
alphaX<-5  #time^-1
alphaY<-1.5  #time^-1
K<-0.5  #conenctration (a.u)
L<-0.3  #conenctration (a.u)
m<-4
n<-4.1
ComS_int<-1  #concentration (a.u)
ComK_int<-1  #concentration (a.u)
times<-seq(0,100,0.001)  #time array

#Initial Condition 1: ComK=0.7 ; ComS=1
X_Null<-seq(0,4,0.001)  #values of ComK (X) 
ComK_Null<-((alphaX/gamma)*X_Null)-(betaX/gamma)*((X_Null^n)/((X_Null^n)+(K^n)))
ComS_Null<-(betaY/alphaY)*((L^m)/((L^m)+(X_Null^m)))
ComS_int1<-1  #concentration (a.u)
ComK_int1<-.7  #concentration (a.u)
p<-c(gamma=gamma,betaX=betaX,betaY=betaY,alphaX=alphaX,alphaY=alphaY,K=K,L=L,m=m,n=n)  #parameters
y01<-c(ComK=ComK_int1,ComS=ComS_int1)  #initial conditions
times<-seq(0,100,0.001)  #time array

library(deSolve)  #ode solver
func<-function(t,y,p){
  ComK<-y[1]
  ComS<-y[2]
  with(as.list(p),{
    dComK<-gamma*ComS+betaX*(ComK^n/((ComK^n)+(K^n)))-alphaX*ComK
    dComS<-betaY*(L^m/((ComK^m)+(L^m)))-alphaY*ComS
    return(list(c(dComK,dComS)))
  })
}
out1<-ode(y=y01,times,func,p)  #call ODE solver


#Initial Condition 2: ComK=1 ; ComS=.7
X_Null<-seq(0,4,0.001)  #values of ComK (X) 
ComK_Null<-((alphaX/gamma)*X_Null)-(betaX/gamma)*((X_Null^n)/((X_Null^n)+(K^n)))
ComS_Null<-(betaY/alphaY)*((L^m)/((L^m)+(X_Null^m)))

p<-c(gamma=gamma,betaX=betaX,betaY=betaY,alphaX=alphaX,alphaY=alphaY,K=K,L=L,m=m,n=n)  #parameters
ComS_int2<-.7  #concentration (a.u)
ComK_int2<-1  #concentration (a.u)
y02<-c(ComK=ComK_int2,ComS=ComS_int2)  #initial conditions
times<-seq(0,100,0.001)  #time array

func<-function(t,y,p){
  ComK<-y[1]
  ComS<-y[2]
  with(as.list(p),{
    dComK<-gamma*ComS+betaX*(ComK^n/((ComK^n)+(K^n)))-alphaX*ComK
    dComS<-betaY*(L^m/((ComK^m)+(L^m)))-alphaY*ComS
    return(list(c(dComK,dComS)))
  })
}
out2<-ode(y=y02,times,func,p)  #call ODE solver


#Initial Condition 3: ComK=.7 ; ComS=.7
X_Null<-seq(0,4,0.001)  #values of ComK (X) 
ComK_Null<-((alphaX/gamma)*X_Null)-(betaX/gamma)*((X_Null^n)/((X_Null^n)+(K^n)))
ComS_Null<-(betaY/alphaY)*((L^m)/((L^m)+(X_Null^m)))

p<-c(gamma=gamma,betaX=betaX,betaY=betaY,alphaX=alphaX,alphaY=alphaY,K=K,L=L,m=m,n=n)  #parameters
ComS_int3<-.7  #concentration (a.u)
ComK_int3<-.7  #concentration (a.u)
y03<-c(ComK=ComK_int3,ComS=ComS_int3)  #initial conditions
times<-seq(0,100,0.001)  #time array

func<-function(t,y,p){
  ComK<-y[1]
  ComS<-y[2]
  with(as.list(p),{
    dComK<-gamma*ComS+betaX*(ComK^n/((ComK^n)+(K^n)))-alphaX*ComK
    dComS<-betaY*(L^m/((ComK^m)+(L^m)))-alphaY*ComS
    return(list(c(dComK,dComS)))
  })
}
out3<-ode(y=y03,times,func,p)  #call ODE solver

plot(X_Null,ComK_Null,type="l",xlab="[ComS]",ylab="[ComK]",main="[ComS] vs. [ComK] (Nullclines in the phase plane)",col=cl[1],xlim=c(0,1),ylim=c(0,2))
lines(X_Null,ComS_Null,col=cl[2])
lines(out1[,2],out1[,3],col=cl[3])
lines(out2[,2],out2[,3],col=cl[4])
lines(out3[,2],out3[,3],col=cl[5])
legend("topright", inset = 0.00, legend=c("[ComS]","[ComK]","Trajectory1","Trajectory 2", "Trajectory 3"), fill=c(cl[1],cl[2],cl[3],cl[4],cl[5]))


```
#10 (cont'd)
Trajectory undergoes signficiant change as a result of monostability (alteration to parameter AlphaY). There is no longer the circular relationship observable when under original parameters. Though comparable relationships can be observed between the components' concentrations, once the fixed point is reached, the trajectory is discontinued, effectively eliminating the looping effect observed under normal conditions. Thus, a lack of fluctuation (steady state) prevents cycling. This is applicable to the trajectories observed under various initial conditions.

The fixed point for this system is, once again, stable (all eigenvalues have negative real parts). This fixed point corresponds with cells' ability to stochastically switch (oscillate) with states characterized by higher K and M values. Additionally, for low values of ComS, a single fixed point corresponds with the vegetative state; this system produces only one fixed point. 

# Part IV: Bistability - *Genetic Switch*

```{R #11,12: Prevent oscillations (tuning parameters)}
cl=rainbow(2)
gamma<-1  #time^-1
betaX<-6.5  #concentration/time; INCREASE
betaY<-1  #concentration/time
alphaX<-5  #time^-1
alphaY<-0.3  #time^-1
K<-0.7  #conenctration (a.u); INCREASE
L<-0.2  #conenctration (a.u); DECREASE
m<-2  #DECREASE
n<-3
ComS_int<-1  #concentration (a.u)
ComK_int<-1  #concentration (a.u)

p<-c(gamma=gamma,betaX=betaX,betaY=betaY,alphaX=alphaX,alphaY=alphaY,K=K,L=L,m=m,n=n)  #parameters
y0<-c(ComK=ComK_int,ComS=ComS_int)  #initial conditions
times<-seq(0,100,0.001)  #time array

library(deSolve)  #ode solver
func<-function(t,y,p){
  ComK<-y[1]
  ComS<-y[2]
  with(as.list(p),{
    dComK<-gamma*ComS+betaX*(ComK^n/((ComK^n)+(K^n)))-alphaX*ComK
    dComS<-betaY*(L^m/((ComK^m)+(L^m)))-alphaY*ComS
    return(list(c(dComK,dComS)))
  })
}
out<-ode(y=y0,times,func,p)  #call ODE solver
plot(out[,1],out[,2],type="l",xlab="Time",ylab="Concentration (a.u)", main="ComK,ComS Concentrations over Time", col=cl[1],ylim=c(0,2))  
lines(out[,1],out[,3],col=cl[2])
legend("topright", legend=c("[ComK]","[ComS]"), fill =cl[1:2])
```
#11 (cont'd)
(Basic Observations, not answer)
As alphaX decreases, the degree of stochasticity decreases with it. Oscillations in [ComK] increase in wavelength before disappearing at roughly alphaX=5.5. A significant enough reduction in gamma (gamma>0.4) eliminates oscillation in [ComK]. One stady state is still observed (albeit it at~concentration=1a.u; same thing for reduction in alphaX)
- When BetaYis reduced to .3 concentration/Time, oscillation seizes and a single steady state can be observed at concentration =~0.3
- Similarly, at AlphaY=.1, oscillation seizes
___
(ANSWER)
BetaX increased, K increased, L decreased, m decreased 

#12 (cont'd): Observations
The plot of concentrations vs time for bistable character does not resemble the plot for original parameters; the plot for monostability was comparable to this original system over a small area of domain. Additionally, the concentration at which each arrives at the steady state differs drastically from  the monostable system--the steady state is achieved at a higher concentration than ComS, opposite to the monostable system. 

```{R #13: Nullclines, lowered alphaY}
cl<-rainbow(2)
gamma<-1  #time^-1
betaX<-6.5  #concentration/time; INCREASE
betaY<-1  #concentration/time
alphaX<-5  #time^-1
alphaY<-0.3  #time^-1
K<-0.7  #conenctration (a.u); INCREASE
L<-0.2  #conenctration (a.u); DECREASE
m<-2  #DECREASE
n<-3
ComS_int<-1  #concentration (a.u)
ComK_int<-1  #concentration (a.u)
times<-seq(0,100,0.001)  #time array

X_Null<-seq(0,2,0.01)  #values of ComK (X) 
ComK_Null<-((alphaX/gamma)*X_Null)-(betaX/gamma)*((X_Null^n)/((X_Null^n)+(K^n)))
ComS_Null<-(betaY/alphaY)*((L^m)/((L^m)+(X_Null^m)))

plot(X_Null,ComK_Null,type="l",xlab="[ComS]",ylab="[ComK]",main="[ComS] vs. [ComK] (Nullclines in the phase plane)",col=cl[1],xlim=c(0,2),ylim=c(0,2))
lines(X_Null,ComS_Null,col=cl[2])
legend("topright", legend=c("[ComS]","[ComK]"), fill =cl[1:2])

```
#13 (cont'd)
Three fixed points exist for the bistable system: FP #1 (0.35,1); FP #2 (0.7,0.25); FP #3 (0.97,0.2) Form: ([ComS],[ComK]). At these concentrations, the system exhibits no fluctuation,as dComK/dt and dComS/dt are both equal to 0. There are triple the number of fixed points observed for this bistable system compared with the monostable system. High expression of ComK leads to cells' expression of the K-state. Bistability is the result of autoregulation of ComK. 

```{R #14: Altered Nullclines + Trajectory Visual}
cl<-rainbow(2)
gamma<-1  #time^-1
betaX<-6.5  #concentration/time; INCREASE
betaY<-1  #concentration/time
alphaX<-5  #time^-1
alphaY<-0.3  #time^-1
K<-0.7  #concentration (a.u); INCREASE
L<-0.2  #concentration (a.u); DECREASE
m<-2  #DECREASE
n<-3
ComS_int<-1  #concentration (a.u)
ComK_int<-1  #concentration (a.u)
times<-seq(0,100,0.001)  #time array

X_Null<-seq(0,4,0.001)  #values of ComK (X) 
ComK_Null<-((alphaX/gamma)*X_Null)-(betaX/gamma)*((X_Null^n)/((X_Null^n)+(K^n)))
ComS_Null<-(betaY/alphaY)*((L^m)/((L^m)+(X_Null^m)))

p<-c(gamma=gamma,betaX=betaX,betaY=betaY,alphaX=alphaX,alphaY=alphaY,K=K,L=L,m=m,n=n)  #parameters
y0<-c(ComK=ComK_int,ComS=ComS_int)  #initial conditions
times<-seq(0,100,0.001)  #time array

library(deSolve)  #ode solver
func<-function(t,y,p){
  ComK<-y[1]
  ComS<-y[2]
  with(as.list(p),{
    dComK<-gamma*ComS+betaX*(ComK^n/((ComK^n)+(K^n)))-alphaX*ComK
    dComS<-betaY*(L^m/((ComK^m)+(L^m)))-alphaY*ComS
    return(list(c(dComK,dComS)))
  })
}
out<-ode(y=y0,times,func,p)  #call ODE solver

plot(X_Null,ComK_Null,type="l",xlab="[ComS]",ylab="[ComK]",main="[ComS] vs. [ComK] (Nullclines in the phase plane)",col=cl[1],xlim=c(0,2),ylim=c(0,2))
lines(X_Null,ComS_Null,col=cl[2])
lines(out[,2],out[,3],col="purple")


legend("topright", inset = 0.0, legend=c("[ComS]","[ComK]","Concentration Trajectory"), fill=c(cl[1],cl[2],"purple"))
```

#14 (cont'd)
FP #1 marks the transition into the vegetative state, where the cell remains until FP #2. Once FP#2 is reached, the cell exists in the competent state for a short time before reaching the vegative state once again at FP #3. 

Recall that ComK as a transcription factor activates expression of a suite of genes that control competence, and that it activates its own gene expression via a positive feedback loop that is critical for the induction of competence in the system. Also recall that ComK is rapidly degraded (via MecA complex); however there is competitive inhibition of degradation by ComS. (ComK also contributes to an indirect negative feedback loop wherein it inhibits ComS expression, which allows for further inhibition of ComK by MecA). 

Protein modulation is essential for cells' responsiveness to intracellular stimuli, or to improper regulation; it is important for steady state to be maintained across various environments. 

# Part V: Bistability - *Genetic Switch*
```{R Excitable Parameter Reference}
gamma<-10  #time^-1
betaX<-30  #concentration/time
n<-5
K<-0.6  #concentration (a.u)
alphaX<-40  #time^-1
betaY<-3  #concentration/time
m<-3
L<-0.47  #excitable "L"
alphaY <-1.5  #time^-1
```

```{R #15,16: New 2D ODE System}
cl<-rainbow(2)
gamma<-10  #time^-1
betaX<-30  #concentration/time
n<-5
K<-0.6  #concentration (a.u)
alphaX<-40  #time^-1
betaY<-3  #concentration/time
m<-3
L<-0.47  #excitable "L"
alphaY <-1.5  #time^-1
#r1<-runif(1)
noise<-0.09

#New ftn
p<-c(gamma=gamma,betaX=betaX,betaY=betaY,alphaX=alphaX,alphaY=alphaY,K=K,L=L,m=m,n=n)  #parameters
y0<-c(ComK=ComK_int,ComS=ComS_int)  #initial conditions
times<-seq(0,100,0.001)  #time array!

library(deSolve)  #ode solver
func<-function(t,y,p){
  ComK<-y[1]
  ComS<-y[2]
  with(as.list(p),{
    dComK<-gamma*ComS+(betaX*(ComK^n/(ComK^n+K^n)))-alphaX*ComK+noise*runif(1)
    dComS<-betaY*(L^m/(L^m+ComK^m))-alphaY+noise*runif(1)
    return(list(c(dComK,dComS)))
  })
}
out<-ode(y=y0,times,func,p)
plot(out[,1],out[,2],xlab="Time",ylab="Respective Concentrations (a.u)",main="ComK, ComS Concentrations Over Time",col=cl[1],xlim=c(0,100),type="l")
lines(out[,1],out[,3],col=cl[2])
#Narrow Domain, plt 2
out<-ode(y=y0,times,func,p)
plot(out[,1],out[,2],xlab="Time",ylab="Respective Concentrations (a.u)",main="ComK, ComS Concentrations Over Time",col=cl[1],xlim=c(0,10),type="l")
lines(out[,1],out[,3],col=cl[2])
legend("topright", legend=c("[ComK]","[ComS]"), fill =cl[1:2])

```
#16 - Comment on what you see
In the excited state the frequency of oscillations increased significantly. Additionally, ComK seems to transition toward a steeper decline faster than it previously had, as shown by the intersection of the ComK line plot with that of ComS at the minimum peak of the ComS line. The addition of noise also leads to small deviations from the standard, smooth line achieved without noise. The range over which each line is plotted is comparable to the non-excited standard (original parameters, lack of noise). Overall, the generic behavior of the system is maintained, with the most significant change being the dramatic change in frequency. 

```{R #16: New 2D ODE System}
cl<-rainbow(2)
gamma<-10  #time^-1
betaX<-30  #concentration/time
n<-5
K<-0.6  #concentration (a.u)
alphaX<-40  #time^-1
betaY<-3  #concentration/time
m<-3
L<-0.47  #excitable "L"
alphaY <-1.5  #time^-1
r1<-runif(1)
noise<-0.09

#New ftn
p<-c(gamma=gamma,betaX=betaX,betaY=betaY,alphaX=alphaX,alphaY=alphaY,K=K,L=L,m=m,n=n)  #parameters
y0<-c(ComK=ComK_int,ComS=ComS_int)  #initial conditions
times<-seq(0,100,0.001)  #time array!

library(deSolve)  #ode solver
func<-function(t,y,p){
  ComK<-y[1]
  ComS<-y[2]
  with(as.list(p),{
    dComK<-gamma*ComS+(betaX*(ComK^n/(ComK^n+K^n)))-alphaX*ComK+noise*runif(1)
    dComS<-betaY*(L^m/(L^m+ComK^m))-alphaY+noise*runif(1)
    return(list(c(dComK,dComS)))
  })
}

out<-ode(y=y0,times,func,p)
plot(out[,2],out[,3],xlab="Time",ylab="Respective Concentrations (a.u)",main="ComK, ComS Concentrations Over Time",col="purple",type="l")
```
#More observations
- Another dramatic example of the impact of the addition of noise
- Once again, overall character is maintained

```{R #17}
cl<-rainbow(2)
gamma<-10  #time^-1
betaX<-30  #concentration/time
n<-5
K<-0.6  #concentration (a.u)
alphaX<-40  #time^-1
betaY<-3  #concentration/time
m<-3
L<-0.47  #excitable "L"
alphaY <-1.5  #time^-1
ComS_int<-1  #concentration (a.u)
ComK_int<-1  #concentration (a.u)
times<-seq(0,100,0.001)  #time array

X_Null<-seq(0,2,0.01)  #values of ComK (X) 
ComK_Null<- -1*(betaX/gamma)*(X_Null^n/(X_Null^n+K^n))+((alphaX*X_Null)/gamma)-((noise*runif(1))/gamma)
ComS_Null<-(betaY/alphaY)*(L^m/(L^m+X_Null^m))+((noise*runif(1))/alphaY)

plot(X_Null,ComK_Null,type="l",xlab="[ComS]",ylab="[ComK]",main="[ComS] vs. [ComK] (Nullclines in the phase plane)",col=cl[1],xlim=c(0,2),ylim=c(0,2))
lines(X_Null,ComS_Null,col=cl[2])
legend("topright", legend=c("[ComS]","[ComK]"), fill =cl[1:2])
```
#17 (cont'd)
The nullclines cross at roughly [ComS]=0.45 and [ComK]=1.2. Steady state is achieved at these concentrations. Note that the addition of noise does not impact the plot of the nullclines. There is a notable climb in the concentration of ComK at this point compared with [ComK] in the non-excited state with standard parameters. 

```{R #18}
cl<-rainbow(5)
gamma<-10  #time^-1
betaX<-30  #concentration/time
n<-5
K<-0.6  #concentration (a.u)
alphaX<-40  #time^-1
betaY<-3  #concentration/time
m<-3
L<-0.47  #excitable "L"
alphaY <-1.5  #time^-1
ComS_int<-1  #concentration (a.u)
ComK_int<-1  #concentration (a.u)
times<-seq(0,100,0.001)  #time array
r1<-runif(1)

X_Null<-seq(0,2,0.01)  #values of ComK (X) 
ComK_Null<- -1*(betaX/gamma)*(X_Null^n/(X_Null^n+K^n))+((alphaX*X_Null)/gamma)-((noise*runif(1))/gamma)
ComS_Null<-(betaY/alphaY)*(L^m/(L^m+X_Null^m))+((noise*runif(1))/alphaY)

p<-c(gamma=gamma,betaX=betaX,betaY=betaY,alphaX=alphaX,alphaY=alphaY,K=K,L=L,m=m,n=n)  #parameters
y0<-c(ComK=ComK_int,ComS=ComS_int)  #initial conditions
times<-seq(0,100,0.001)  #time array!
noise1<-0.09
noise2<-0.18
noise3<-0.045

library(deSolve)  #ode solver
func1<-function(t,y,p){
  ComK<-y[1]
  ComS<-y[2]
  with(as.list(p),{
    dComK1<-gamma*ComS+(betaX*(ComK^n/(ComK^n+K^n)))-alphaX*ComK+noise*runif(1)
    dComS1<-betaY*(L^m/(L^m+ComK^m))-alphaY+noise1*runif(1)
    return(list(c(dComK1,dComS1)))
  })
}
out1<-ode(y=y0,times,func1,p)

library(deSolve)  #ode solver
func2<-function(t,y,p){

  ComK<-y[1]
  ComS<-y[2]
  with(as.list(p),{
    dComK2<-gamma*ComS+(betaX*(ComK^n/(ComK^n+K^n)))-alphaX*ComK+noise*runif(1)
    dComS2<-betaY*(L^m/(L^m+ComK^m))-alphaY+noise2*runif(1)
    return(list(c(dComK2,dComS2)))
  })
}
out2<-ode(y=y0,times,func2,p)

library(deSolve)  #ode solver
func3<-function(t,y,p){

  ComK<-y[1]
  ComS<-y[2]
  with(as.list(p),{
    dComK3<-gamma*ComS+(betaX*(ComK^n/(ComK^n+K^n)))-alphaX*ComK+noise*runif(1)
    dComS3<-betaY*(L^m/(L^m+ComK^m))-alphaY+noise3*runif(1)
    return(list(c(dComK3,dComS3)))
  })
}
out3<-ode(y=y0,times,func3,p)

plot(X_Null,ComK_Null,type="l",xlab="[ComS]",ylab="[ComK]",main="[ComS] vs. [ComK] (Nullclines in the phase plane)",col=cl[1],xlim=c(0,2),ylim=c(0,2))
lines(X_Null,ComS_Null,col=cl[2])
lines(out1[,2],out1[,3],col=cl[3])
legend("topright", legend=c("[ComK]","[ComS]","Trajectory Noise Original"), fill=c(cl[1],cl[2],cl[3]))

plot(X_Null,ComK_Null,type="l",xlab="[ComS]",ylab="[ComK]",main="[ComS] vs. [ComK] (Nullclines in the phase plane)",col=cl[1],xlim=c(0,2),ylim=c(0,2))
lines(X_Null,ComS_Null,col=cl[2])
lines(out2[,2],out2[,3],col=cl[4])
legend("topright", legend=c("[ComK]","[ComS]","Trajectory Noise Elevated"), fill=c(cl[1],cl[2],cl[4]))

plot(X_Null,ComK_Null,type="l",xlab="[ComS]",ylab="[ComK]",main="[ComS] vs. [ComK] (Nullclines in the phase plane)",col=cl[1],xlim=c(0,2),ylim=c(0,2))
lines(X_Null,ComS_Null,col=cl[2])
lines(out3[,2],out3[,3],col=cl[5])
legend("topright", legend=c("[ComK]","[ComS]","Trajectory Noise Lowered"), fill=c(cl[1],cl[2],cl[5]))
```

#18 (cont'd)
As the value for noise increases, the space (in both the x and y direction) in which lines appear surrounding the would-be trajectory (sans-noise) increases. The opposite is true when the value for noise decreases. This can be observed in the above graphs, the first of which is the standard 0.09 value; the second is doubled, and the third is halved. Regardless of the size, the addition of any noise to the size increases the range of concentrations over which a response will be generated from the B. subtilis. In other words, the range over which B. subtilis' competence cycle/circuit exists is expanded by the introduction of noise. This noise can be generated by a number of events including RNA/protein synthesis or degradation, and protein binding/unbdinding to the DNA. Transcription within B. subtilis is controlled by the circuit referenced. It is logical that, as the degree to which thes events occur increases, the area over which the trajectory exists increases and with it the range over which the competence cycle exists. The cell is in the vegetative state.





